title: Dominic Correlli
logo: /assets/img/logo.png
description: Data Analyst â€¢ Supply Chain & Operations Research
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
